Create new note
nancy-binani/wheel pull request #13
Opened 2022-09-22 11:45 UTC by nancy-binani

2022-09-22 11:54 UTC, yedhink commented
@nancy-binani I will review this PR once you go through https://handbook.neetokb.com/articles/git-and-github-essentials and fix the issues.

I believe this is the [second time](https://github.com/nancy-binani/wheel/pull/8#issuecomment-1252388392) I am pointing this out. Lemme know if something is not clear in the article.

2022-09-22 12:00 UTC, nancy-binani commented
I am really sorry this mistake won't happen again.

2022-09-22 12:10 UTC, yedhink requested changes
@nancy-binani

2022-09-22 12:10 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/List/index.jsx
> +import React from "react";
The List folder only has one file. Which is suggesting to us that we don't need a folder for it in the fist place. Thus keep this logic within `Notes/List.jsx`

2022-09-22 12:10 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/List/index.jsx
> +                name: "Nancy",
Go through the Slack thread. I have pointed out about personas to be use.

2022-09-22 12:10 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +
Go through the Slack thread. We can build these values by creating a util called something like `buildSelectOptions`.

2022-09-22 12:10 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +    .min(1, "Please select a tag")
Here the error message can be made more specific. Here we should be pointing out that atleast one tag ought to be selected. That suggests two things:
- The least amount of tags needed
- More than one tag can also be selected

2022-09-22 16:28 UTC, nancy-binani commented
I have added the required changes.Please review them.

2022-09-22 16:49 UTC, yedhink commented
@nancy-binani Already provided the reviews.

2022-09-22 18:06 UTC, nancy-binani commented
I meant I have done all the changes. So please review them.

2022-09-22 18:25 UTC, nancy-binani commented
This message was like my final message which informs all the review changes are done.So you can review them altogether.

2022-09-22 20:00 UTC, yedhink requested changes
@nancy-binani

2022-09-22 20:00 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/List.jsx
> +import { MENU_OPTIONS as menuOptions } from "./constants";
https://academy.bigbinary.com/learn-react/pages/naming-conventions-in-react#:~:text=Use%20upper%20snake%20case%20in%20constant%20name

2022-09-23 03:36 UTC, nancy-binani commented
I have updated according to namespacing comventions.

2022-09-23 12:04 UTC, merged